### ISSUE TITLE
poissonRelax works with MPI, gives correct answer for 2 processes but not 4

### ISSUE THREAD

**Issue by dumas2** [dumas2/chymera-uo#1]
# Possible problems

Exchange halo subroutine added to poissonRelax.F90
_or_
readRho subroutine in io.F90

**Comment by rasmussn** [comment]
Does this mean you have the MPI stuff working?

-craig

**Comment by dumas2** [comment]
Hi Craig,

Yes, I got the Poisson solver working in MPI. It calculates the boundary 
conditions, does the FFT and uses a multigrid algorithm with a single 
V-cycle to solve for the potential. So far it agrees with the OpenMP 
version on a small grid.

Are you around for the summer?

William
